// <auto-generated />
using Astick.Theatre.Data;
using Astick.Theatre.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Astick.Theatre.Migrations
{
    [DbContext(typeof(Cl_AppDbContext))]
    partial class Cl_AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_Hall", b =>
                {
                    b.Property<Guid>("p_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("F_ID");

                    b.Property<string>("p_Address")
                        .HasColumnName("F_ADDRESS");

                    b.Property<string>("p_Description")
                        .HasColumnName("F_DESC");

                    b.Property<string>("p_Name")
                        .HasColumnName("F_NAME");

                    b.Property<int>("p_RowNumbersCountAmphitheater")
                        .HasColumnName("F_ROW_NUMBERS_COUNT_AMPHITHEATER");

                    b.Property<int>("p_RowNumbersCountBalcony")
                        .HasColumnName("F_ROW_NUMBERS_COUNT_Balcony");

                    b.Property<int>("p_RowNumbersCountLodges")
                        .HasColumnName("F_ROW_NUMBERS_COUNT_LODGES");

                    b.Property<int>("p_RowNumbersCountMezzanine")
                        .HasColumnName("F_ROW_NUMBERS_COUNT_MEZZANINE");

                    b.Property<int>("p_RowNumbersCountParquet")
                        .HasColumnName("F_ROW_NUMBERS_COUNT_PARQUET");

                    b.Property<int>("p_RowsCountAmphitheater")
                        .HasColumnName("F_ROWS_COUNT_AMPHITHEATER");

                    b.Property<int>("p_RowsCountBalcony")
                        .HasColumnName("F_ROWS_COUNT_Balcony");

                    b.Property<int>("p_RowsCountLodges")
                        .HasColumnName("F_ROWS_COUNT_LODGES");

                    b.Property<int>("p_RowsCountMezzanine")
                        .HasColumnName("F_ROWS_COUNT_MEZZANINE");

                    b.Property<int>("p_RowsCountParquet")
                        .HasColumnName("F_ROWS_COUNT_PARQUET");

                    b.HasKey("p_ID");

                    b.ToTable("T_HALL");
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_LogsHalls", b =>
                {
                    b.Property<Guid>("p_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("F_ID");

                    b.Property<DateTime>("p_Date")
                        .HasColumnName("F_DATE");

                    b.Property<decimal>("p_Price")
                        .HasColumnName("F_PRICE");

                    b.Property<Guid?>("p_PromoCodeID")
                        .HasColumnName("F_PROMO_CODE_ID");

                    b.Property<Guid>("p_SeatID")
                        .HasColumnName("F_SEAT_ID");

                    b.Property<int>("p_TypeEmployment")
                        .HasColumnName("F_TYPE_EMPLOYMENT");

                    b.Property<Guid>("p_UserID")
                        .HasColumnName("F_USER_ID");

                    b.HasKey("p_ID");

                    b.HasIndex("p_PromoCodeID");

                    b.HasIndex("p_SeatID");

                    b.HasIndex("p_UserID");

                    b.ToTable("T_LOGS_HALLS");
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_PromoCode", b =>
                {
                    b.Property<Guid>("p_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("F_ID");

                    b.Property<string>("p_Code")
                        .IsRequired()
                        .HasColumnName("F_CODE")
                        .HasMaxLength(50);

                    b.Property<DateTime>("p_DateEnd")
                        .HasColumnName("F_DATE_END")
                        .HasColumnType("date");

                    b.Property<DateTime>("p_DateStart")
                        .HasColumnName("F_DATE_START")
                        .HasColumnType("date");

                    b.Property<string>("p_Description")
                        .HasColumnName("F_DESC");

                    b.Property<decimal>("p_Discount")
                        .HasColumnName("F_DISCOUNT")
                        .HasColumnType("decimal(17,14)");

                    b.Property<string>("p_Name")
                        .IsRequired()
                        .HasColumnName("F_NAME");

                    b.HasKey("p_ID");

                    b.ToTable("T_PROMO_CODES");
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<string>("p_Description")
                        .HasColumnName("F_DESCRIPTION");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_Seat", b =>
                {
                    b.Property<Guid>("p_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("F_ID");

                    b.Property<string>("p_Comment")
                        .HasColumnName("F_COMMENT");

                    b.Property<string>("p_Mobile")
                        .HasColumnName("F_MOBILE");

                    b.Property<int>("p_Number")
                        .HasColumnName("F_NUMBER");

                    b.Property<decimal>("p_Price")
                        .HasColumnName("F_PRICE");

                    b.Property<Guid?>("p_PromoCodeID")
                        .HasColumnName("F_PROMO_CODE_ID");

                    b.Property<int>("p_Row")
                        .HasColumnName("F_ROW");

                    b.Property<Guid>("p_SessionID")
                        .HasColumnName("F_SESSION_ID");

                    b.Property<decimal>("p_TotalPrice")
                        .HasColumnName("F_TOTALPRICE");

                    b.Property<int>("p_Type")
                        .HasColumnName("F_TYPE");

                    b.Property<int>("p_TypeEmployment")
                        .HasColumnName("F_TYPE_EMPLOYMENT");

                    b.Property<string>("p_UserFIO")
                        .HasColumnName("F_USER_FIO");

                    b.HasKey("p_ID");

                    b.HasIndex("p_PromoCodeID");

                    b.HasIndex("p_SessionID");

                    b.ToTable("T_SEATS");
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_Session", b =>
                {
                    b.Property<Guid>("p_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("F_ID");

                    b.Property<DateTime>("p_Date")
                        .HasColumnName("F_DATE");

                    b.Property<string>("p_Description")
                        .HasColumnName("F_DESC");

                    b.Property<Guid>("p_HallID")
                        .HasColumnName("F_HALL_ID");

                    b.Property<string>("p_Name")
                        .HasColumnName("F_NAME");

                    b.Property<decimal>("p_PriceAmphitheater")
                        .HasColumnName("F_PRICE_AMPHITHEATER");

                    b.Property<decimal>("p_PriceBalcony")
                        .HasColumnName("F_PRICE_BALCONY");

                    b.Property<decimal>("p_PriceLodges")
                        .HasColumnName("F_PRICE_LODGES");

                    b.Property<decimal>("p_PriceMezzanine")
                        .HasColumnName("F_PRICE_MEZZANINE");

                    b.Property<decimal>("p_PriceParquet")
                        .HasColumnName("F_PRICE_PARQUET");

                    b.HasKey("p_ID");

                    b.HasIndex("p_HallID");

                    b.ToTable("T_SESSION");
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("p_Address")
                        .HasColumnName("F_ADDRESS");

                    b.Property<DateTime?>("p_Birthday")
                        .HasColumnName("F_BIRTHDAY");

                    b.Property<string>("p_Comment")
                        .HasColumnName("F_COMMENT");

                    b.Property<DateTime>("p_CreateDate")
                        .HasColumnName("F_DATE_CREATE");

                    b.Property<bool>("p_IsLockedOut");

                    b.Property<string>("p_LastName")
                        .HasColumnName("F_LASTNAME");

                    b.Property<string>("p_Mobile")
                        .HasColumnName("F_MOBILE");

                    b.Property<string>("p_Name")
                        .HasColumnName("F_NAME");

                    b.Property<string>("p_SurName")
                        .HasColumnName("F_SURNAME");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_LogsHalls", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_PromoCode", "p_PromoCode")
                        .WithMany()
                        .HasForeignKey("p_PromoCodeID");

                    b.HasOne("Astick.Theatre.Entities.Cl_Seat", "p_Seat")
                        .WithMany()
                        .HasForeignKey("p_SeatID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Astick.Theatre.Entities.Cl_User", "p_User")
                        .WithMany()
                        .HasForeignKey("p_UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_Seat", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_PromoCode", "p_PromoCode")
                        .WithMany()
                        .HasForeignKey("p_PromoCodeID");

                    b.HasOne("Astick.Theatre.Entities.Cl_Session", "p_Session")
                        .WithMany("p_Seats")
                        .HasForeignKey("p_SessionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Astick.Theatre.Entities.Cl_Session", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_Hall", "p_Hall")
                        .WithMany()
                        .HasForeignKey("p_HallID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Astick.Theatre.Entities.Cl_User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Astick.Theatre.Entities.Cl_User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
